action_id: trunk-single-player-auto-upgrade
date: 2024-02-28 03:06:23
run: trunk upgrade cli --single-player-only -n --no-progress --on-upgrade=false --allow-daemon-start=false
run_from: ""
trigger: schedule 24h+1h
result:
  exit_code: 0
  out: ""
  err: ""
timestamp: 1709089583
full_timestamp:
  nanos: 275046000
  seconds: 1709089583
trunk_version: 1.20.1
