@echo off
REM Generated by trunk tool 'bandit'
set PYTHONUTF8=1
set PATH=C:\Users\Admin\AppData\Local\trunk\tools\bandit\1.7.7-7178386b0fcf7082545e59b79465925d/bin;C:\Users\Admin\AppData\Local\trunk\tools\bandit\1.7.7-7178386b0fcf7082545e59b79465925d/Scripts;C:\Users\Admin\AppData\Local\trunk\tools\python\3.10.8-2211cb108575de2785d77a26a1f8d070/bin;C:\Users\Admin\AppData\Local\trunk\tools\python\3.10.8-2211cb108575de2785d77a26a1f8d070;C:\Users\Admin\AppData\Local\trunk\tools\git-bash\2.40.1-da0c3e1526d36e62bf43d06ec46c5052/bin;C:\Users\Admin\AppData\Local\trunk\tools\git-bash\2.40.1-da0c3e1526d36e62bf43d06ec46c5052/usr/bin;%PATH%
set VIRTUAL_ENV=C:\Users\Admin\AppData\Local\trunk\tools\bandit\1.7.7-7178386b0fcf7082545e59b79465925d
set HOME=%HOME%
if not defined HOME set HOME=

start /w /b bandit %*
