@echo off
REM Generated by trunk tool 'black'
set HOME=%HOME%
if not defined HOME set HOME=
set PYTHONUTF8=1
set VIRTUAL_ENV=C:\Users\Admin\AppData\Local\trunk\tools\black\24.2.0-1667d52fc11401891d94ca8844860a28
set PATH=C:\Users\Admin\AppData\Local\trunk\tools\black\24.2.0-1667d52fc11401891d94ca8844860a28/bin;C:\Users\Admin\AppData\Local\trunk\tools\black\24.2.0-1667d52fc11401891d94ca8844860a28/Scripts;C:\Users\Admin\AppData\Local\trunk\tools\python\3.10.8-2211cb108575de2785d77a26a1f8d070/bin;C:\Users\Admin\AppData\Local\trunk\tools\python\3.10.8-2211cb108575de2785d77a26a1f8d070;C:\Users\Admin\AppData\Local\trunk\tools\git-bash\2.40.1-da0c3e1526d36e62bf43d06ec46c5052/bin;C:\Users\Admin\AppData\Local\trunk\tools\git-bash\2.40.1-da0c3e1526d36e62bf43d06ec46c5052/usr/bin;%PATH%

start /w /b black %*
