@echo off
REM Generated by trunk tool 'isort'
set PYTHONUTF8=1
set PATH=C:\Users\Admin\AppData\Local\trunk\tools\isort\5.13.2-7def74b7c92d83d2d8fdff8ddb752c87/bin;C:\Users\Admin\AppData\Local\trunk\tools\isort\5.13.2-7def74b7c92d83d2d8fdff8ddb752c87/Scripts;C:\Users\Admin\AppData\Local\trunk\tools\python\3.10.8-2211cb108575de2785d77a26a1f8d070/bin;C:\Users\Admin\AppData\Local\trunk\tools\python\3.10.8-2211cb108575de2785d77a26a1f8d070;C:\Users\Admin\AppData\Local\trunk\tools\git-bash\2.40.1-da0c3e1526d36e62bf43d06ec46c5052/bin;C:\Users\Admin\AppData\Local\trunk\tools\git-bash\2.40.1-da0c3e1526d36e62bf43d06ec46c5052/usr/bin;%PATH%
set VIRTUAL_ENV=C:\Users\Admin\AppData\Local\trunk\tools\isort\5.13.2-7def74b7c92d83d2d8fdff8ddb752c87
set HOME=%HOME%
if not defined HOME set HOME=

start /w /b isort %*
