@echo off
REM Generated by trunk tool 'trufflehog'
set PATH=C:\Users\Admin\AppData\Local\trunk\tools\trufflehog\3.68.0-14dceb4dbd1a705b684cd0ed7a6bb524;C:\Users\Admin\AppData\Local\trunk\tools\git-bash\2.40.1-da0c3e1526d36e62bf43d06ec46c5052/bin;C:\Users\Admin\AppData\Local\trunk\tools\git-bash\2.40.1-da0c3e1526d36e62bf43d06ec46c5052/usr/bin;%PATH%

start /w /b trufflehog %*
