@echo off
REM Generated by trunk tool 'trufflehog'
set PATH=C:\Users\Admin\AppData\Local\trunk\tools\trufflehog\3.68.2-ea7b9f8ab5343729b6db589eb60bdf8a;C:\Users\Admin\AppData\Local\trunk\tools\git-bash\2.40.1-da0c3e1526d36e62bf43d06ec46c5052/bin;C:\Users\Admin\AppData\Local\trunk\tools\git-bash\2.40.1-da0c3e1526d36e62bf43d06ec46c5052/usr/bin;%PATH%

start /w /b trufflehog %*
