action_id: trunk-upgrade-available
date: 2024-02-26 00:34:16
run: trunk upgrade --notify --allow-daemon-start=false
run_from: ""
trigger: schedule 1h
result:
  exit_code: 0
  out: "notifications:\r\n  - commands:\r\n      - run: trunk upgrade\r\n        title: all\r\n      - run: trunk upgrade check\r\n        title: Linters\r\n    id: trunk-upgrade\r\n    message: \" 5 linter upgrades\\n\"\r\n    priority: low\r\n    rendered: \"\\x1b[90mRun \\x1b[0m\\x1b[96mtrunk upgrade\\x1b[0m\\x1b[90m to upgrade \\x1b[0m\\x1b[90m5 linters\\n\\x1b[0m\"\r\n    title: Upgrades Available\r\nnotifications_to_delete:\r\n  - trunk-check-upgrade\r\n"
  err: ""
timestamp: 1708907656
full_timestamp:
  nanos: 240452000
  seconds: 1708907656
trunk_version: 1.20.1
action_output:
  notifications:
    - commands:
        - run: trunk upgrade
          title: all
        - run: trunk upgrade check
          title: Linters
      full_timestamp:
        nanos: 240452000
        seconds: 1708907656
      id: trunk-upgrade
      message: " 5 linter upgrades\n"
      priority: low
      rendered: "\x1b[90mRun \x1b[0m\x1b[96mtrunk upgrade\x1b[0m\x1b[90m to upgrade \x1b[0m\x1b[90m5 linters\n\x1b[0m"
      timestamp: 1708907656
      title: Upgrades Available
  notifications_to_delete:
    - trunk-check-upgrade
