action_id: trunk-share-with-everyone
date: 2024-02-28 03:28:58
run: trunk config share --notify --allow-daemon-start=false
run_from: ""
trigger: schedule 24h
result:
  exit_code: 0
  out: "notifications_to_delete:\r\n  - trunk-share-with-everyone\r\n"
  err: ""
timestamp: 1709090938
full_timestamp:
  nanos: 507320000
  seconds: 1709090938
trunk_version: 1.20.1
action_output:
  notifications_to_delete:
    - trunk-share-with-everyone
