action_id: trunk-share-with-everyone
date: 2024-02-28 02:06:23
run: trunk config share --notify --allow-daemon-start=false
run_from: ""
trigger: schedule 24h
result:
  exit_code: 0
  out: "notifications_to_delete:\r\n  - trunk-share-with-everyone\r\n"
  err: ""
timestamp: 1709085983
full_timestamp:
  nanos: 148126000
  seconds: 1709085983
trunk_version: 1.20.1
action_output:
  notifications_to_delete:
    - trunk-share-with-everyone
